r2d2:
    fls_node_tier1:
        ros__parameters:
            optimization_frequency: 30.0
            transaction_timeout: 0.1
            lag_duration: 0.5

            motion_models:
              unicycle_motion_model:
                type: fuse_models::Unicycle2D

            unicycle_motion_model:
              #                         x      y      yaw    vx     vy     vyaw   ax   ay
              process_noise_diagonal: [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.1, 0.1]

            sensor_models:
              initial_localization_sensor:
                type: fuse_models::Unicycle2DIgnition
                motion_models: [unicycle_motion_model]
                ignition: true
              odometry_sensor:
                type: fuse_models::Odometry2D
                motion_models: [unicycle_motion_model]
              visual_odometry_sensor:
                type: fuse_models::Odometry2D
                motion_models: [unicycle_motion_model]
              imu_sensor:
                type: fuse_models::Imu2D
                motion_models: [unicycle_motion_model]

            initial_localization_sensor:
              publish_on_startup: true
              #                  x      y      yaw    vx     vy     vyaw   ax     ay
              initial_state: [  0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
              initial_sigma: [  0.100, 0.100, 0.100, 0.100, 0.100, 0.001, 0.100, 0.001]

            odometry_sensor:
              topic: 'odometry'
              twist_target_frame: 'r2d2/base_link'
              linear_velocity_dimensions: ['x', 'y']
              angular_velocity_dimensions: ['yaw']

            visual_odometry_sensor:
              topic: 'odometry_visual'
              twist_target_frame: 'r2d2/base_link'
              linear_velocity_dimensions: ['x', 'y']
              angular_velocity_dimensions: ['yaw']

            imu_sensor:
              topic: 'imu'
              twist_target_frame: 'r2d2/base_link'
              angular_velocity_dimensions: ['yaw']

            publishers:
              filtered_publisher:
                type: fuse_models::Odometry2DPublisher

            filtered_publisher:
              topic: 'odometry/filtered_tier1_fls'
              base_link_frame_id: 'r2d2/base_link'
              base_link_output_frame_id: 'r2d2/base_link'
              odom_frame_id: 'r2d2/odom'
              map_frame_id: 'map'
              world_frame_id: 'r2d2/odom'
              publish_frequency: 30.0
              publish_tf: true

    fls_node_tier2:
        ros__parameters:
            optimization_frequency: 30.0
            transaction_timeout: 0.1
            lag_duration: 0.5

            motion_models:
              unicycle_motion_model:
                type: fuse_models::Unicycle2D

            unicycle_motion_model:
              #                         x      y      yaw    vx     vy     vyaw   ax   ay
              process_noise_diagonal: [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.1, 0.1]

            sensor_models:
              initial_localization_sensor:
                type: fuse_models::Unicycle2DIgnition
                motion_models: [unicycle_motion_model]
                ignition: true
              odometry_sensor:
                type: fuse_models::Odometry2D
                motion_models: [unicycle_motion_model]
              visual_odometry_sensor:
                type: fuse_models::Odometry2D
                motion_models: [unicycle_motion_model]
              imu_sensor:
                type: fuse_models::Imu2D
                motion_models: [unicycle_motion_model]
#------------> Add the beacon sensor here (no config required)

            initial_localization_sensor:
              publish_on_startup: true
              #                  x      y       yaw    vx     vy     vyaw   ax     ay
              initial_state: [112.87,  5.870,  3.050, 0.000, 0.000, 0.000, 0.000, 0.000]
              initial_sigma: [  0.100, 0.100,  0.100, 0.100, 0.100, 0.001, 0.100, 0.001]

            odometry_sensor:
              topic: 'odometry'
              twist_target_frame: 'r2d2/base_link'
              linear_velocity_dimensions: ['x', 'y']
              angular_velocity_dimensions: ['yaw']

            visual_odometry_sensor:
              topic: 'odometry_visual'
              twist_target_frame: 'r2d2/base_link'
              linear_velocity_dimensions: ['x', 'y']
              angular_velocity_dimensions: ['yaw']

            imu_sensor:
              topic: 'imu'
              twist_target_frame: 'r2d2/base_link'
              angular_velocity_dimensions: ['yaw']

            publishers:
              filtered_publisher:
                type: fuse_models::Odometry2DPublisher

            filtered_publisher:
              topic: 'odometry/filtered_tier2_fls'
              base_link_frame_id: 'r2d2/base_link'
              base_link_output_frame_id: 'r2d2/base_link'
              odom_frame_id: 'r2d2/odom'
              map_frame_id: 'map'
              world_frame_id: 'map'
              publish_frequency: 30.0
              publish_tf: true
